config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get "/:deviceid/:date/show_mains" => "limoes#show_mains", :as => "limoes_show_mains"
get "/:deviceid/:date/show_temperature" => "limoes#show_temperature",  :as => "limoes_show_temperature"
get "/:deviceid/:date/show_temperature_topvalue" => "limoes#show_temperature_topvalue",  :as => "limoes_show_temperature_topvalue"
get "/:deviceid/:date/show_temperature_24h" => "limoes#show_temperature_24h",  :as => "limoes_show_temperature_24h"
get "/:deviceid/:date/show_temperature_boxplot" => "limoes#show_temperature_boxplot",  :as => "limoes_show_temperature_boxplot"
get "/show_index" => "index#index", :as => "show_index"
get "/show_log" => "index#show_log", :as => "show_log"

get "/:deviceid/:date/show_pressure" => "limoes#show_pressure",  :as => "limoes_show_pressure"
get "/:deviceid/:date/show_pressure_topvalue" => "limoes#show_pressure_topvalue",  :as => "limoes_show_pressure_topvalue"
get "/:deviceid/:date/show_pressure_24h" => "limoes#show_pressure_24h",  :as => "limoes_show_pressure_24h"

get "/:deviceid/:sensor/:date/show_speed" => "limoes#show_speed",  :as => "limoes_show_speed"
get "/:deviceid/:sensor/:date/show_speed_topvalue" => "limoes#show_speed_topvalue",  :as => "limoes_show_speed_topvalue"
get "/:deviceid/:sensor/:date/show_speed_24h" => "limoes#show_speed_24h",  :as => "limoes_show_speed_24h"

get "/:deviceid/:date/show_vibration" => "limoes#show_vibration",  :as => "limoes_show_vibration"
get "/:deviceid/:date/show_vibration_topvalue" => "limoes#show_vibration_topvalue",  :as => "limoes_show_vibration_topvalue"
get "/:deviceid/:date/show_vibration_24h" => "limoes#show_vibration_24h",  :as => "limoes_show_vibration_24h"

end

app/controllers/limoes_controller.rb
require 'rest-client'
require 'json'



class LimoesController < ApplicationController

  def show_mains
deviceid = params[:deviceid]
date = params[:date]

  testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/last7restart", {"date"=>date,"deviceid"=>deviceid}.to_json, {content_type: :json, accept: :json}
  testjson = JSON.parse(testbody)

  @totalSpendtime =testjson['totalSpendtime'][0]['totalSpendtime']


  devicelist =  testjson['devicelist']
  avglist =  testjson['AvgSpendtimeList']
  @datelist =[]
  @spendtimes = []
  @restarts = []
  @avgSpendtimes = []

@avgSpendtime = 0
@restart = 0
@spendtime = 0


devicelist.each {|x|
@datelist.push(x['date'].to_s);
@spendtimes.push(x['spendtime']);
@restarts.push(x['restartCount']);
if x['date'] == date
@restart = x['restartCount']
@spendtime = x['spendtime']
@avgSpendtime = x['avgSpendtime']

end
}
avglist.each {|x|
@avgSpendtimes.push(x['avgSpendtime']);
if x['date'] == date
@avgSpendtime = x['avgSpendtime']
end
}

sumbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/getPeriodExceed", {"date"=>date,"deviceid"=>deviceid}.to_json, {content_type: :json, accept: :json}
sumjson = JSON.parse(sumbody)

period_array = sumjson['timePeriodSum']
@periodlist = []
@sumlist = []
@sumcount = 0

period_array.each {|x|

@periodlist.push(x['timePeriod'])
@sumlist.push(x['sum'])
@sumcount+= x['sum']
}



    render :layout => "application_page"
  end

  def show_temperature
    deviceid = params[:deviceid]
    date = params[:date]
testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData//last7MaxMin", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0092"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)

@datelist = []
@l92_list_max = []
@l92_list_avg = []

l92_list = testjson['sensorMaxMinlist']

l92_list.each { |x|
 @datelist.push(x['date'])
 @l92_list_max.push(x['max'])
 @l92_list_avg.push(x['avg'])
}

testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData//last7MaxMin", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0080"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)

@l80_list_max = []
@l80_list_avg = []

l80_list = testjson['sensorMaxMinlist']

l80_list.each { |x|
 @l80_list_max.push(x['max'])
 @l80_list_avg.push(x['avg'])
}



testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData//last7MaxMin", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0075"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)

@l75_list_max = []
@l75_list_avg = []

l75_list = testjson['sensorMaxMinlist']

l75_list.each { |x|
 @l75_list_max.push(x['max'])
 @l75_list_avg.push(x['avg'])
}



    render :layout => "application_page"
  end

  def show_temperature_topvalue

deviceid = params[:deviceid]
date = params[:date]

testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData//last7MaxMin", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0092"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@datelist = []
@l92_list_max = []

l92_list = testjson['sensorMaxMinlist']

l92_list.each { |x|
 @datelist.push(x['date'])
 @l92_list_max.push(x['max'])
}


testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData//last7MaxMin", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0080"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@l80_list_max = []

l80_list = testjson['sensorMaxMinlist']

l80_list.each { |x|
 @l80_list_max.push(x['max'])
}


testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData//last7MaxMin", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0075"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@l75_list_max = []

l75_list = testjson['sensorMaxMinlist']

l75_list.each { |x|
 @l75_list_max.push(x['max'])
}

testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/last7TopValue", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0092"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@l92_list_topvalue = []


l92_list = testjson['sensorTopValuelist']

l92_list.each { |x|
 @l92_list_topvalue.push(x['topvalue'])
}


testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/last7TopValue", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0080"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@l80_list_topvalue = []


l80_list = testjson['sensorTopValuelist']

l80_list.each { |x|
 @l80_list_topvalue.push(x['topvalue'])
}

testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/last7TopValue", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0075"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@l75_list_topvalue = []


l75_list = testjson['sensorTopValuelist']

l75_list.each { |x|
 @l75_list_topvalue.push(x['topvalue'])
}



    render :layout => "application_page"
  end

  def show_temperature_24h

    deviceid = params[:deviceid]
date = params[:date]

    testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/getSensorHour", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0092"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@hourlist = []
@l92_list_max = []
@l92_list_avg = []

l92_list = testjson['sensorHourlist']

l92_list.each { |x|
 @hourlist.push(x['hour'])
 @l92_list_max.push(x['max'])
 @l92_list_avg.push(x['avg'])
}

    testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/getSensorHour", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0080"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)



@l80_list_max = []
@l80_list_avg = []

l80_list = testjson['sensorHourlist']

l80_list.each { |x|
 @hourlist.push(x['date'])
 @l80_list_max.push(x['max'])
 @l80_list_avg.push(x['avg'])
}

testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/getSensorHour", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0075"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)



@l75_list_max = []
@l75_list_avg = []

l75_list = testjson['sensorHourlist']

l75_list.each { |x|
 @hourlist.push(x['date'])
 @l75_list_max.push(x['max'])
 @l75_list_avg.push(x['avg'])
}


    render :layout => "application_page"
  end


  def show_temperature_boxplot
date = params[:date]
    testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/last7Boxplot", {"date"=>date,"sensor"=>"L0080"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


totalList =testjson['sensorBoxplotList']

@boxplot_list = []


totalList.each { |x|

 lower =  x['lower']
 if(lower <0)
  lower = 0
 end
 q1 = x['q1']
 median = x['median']
 q3 = x['q3']
 upper = x['upper']
 boxplot = [lower,q1,median,q3,upper]

 @boxplot_list.push(boxplot)
}

    render :layout => "application_page"
  end


  def show_pressure
    deviceid = params[:deviceid]
    date = params[:date]
testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData//last7MaxMin", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0065"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)

@datelist = []
@l65_list_max = []
@l65_list_min = []


l65_list = testjson['sensorMaxMinlist']

l65_list.each { |x|
 @datelist.push(x['date'])
 @l65_list_max.push(x['max'])
 @l65_list_min.push(x['min'])

}

testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData//last7MaxMin", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0010"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)

@l10_list_max = []
@l10_list_min = []

l10_list = testjson['sensorMaxMinlist']

l10_list.each { |x|
 @l10_list_max.push(x['max'])
 @l10_list_min.push(x['min'])
}





    render :layout => "application_page"
  end

  def show_pressure_topvalue

deviceid = params[:deviceid]
date = params[:date]

testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData//last7MaxMin", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0065"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@datelist = []
@l65_list_avg = []

l65_list = testjson['sensorMaxMinlist']

l65_list.each { |x|
 @datelist.push(x['date'])
 @l65_list_avg.push(x['avg'])
}


testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData//last7MaxMin", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0010"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@l10_list_avg = []

l10_list = testjson['sensorMaxMinlist']

l10_list.each { |x|
 @l10_list_avg.push(x['avg'])
}



testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/last7TopValue", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0065"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@l65_list_topvalue = []


l65_list = testjson['sensorTopValuelist']

l65_list.each { |x|
 @l65_list_topvalue.push(x['topvalue'])
}


testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/last7TopValue", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0010"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@l10_list_topvalue = []


l10_list = testjson['sensorTopValuelist']

l10_list.each { |x|
 @l10_list_topvalue.push(x['topvalue'])
}


    render :layout => "application_page"
  end

  def show_pressure_24h

    deviceid = params[:deviceid]
date = params[:date]

    testbody = RestClient.post "http://10.76.2.63:8080/gcis/getResData/getSensorHour", {"date"=>date,"deviceid"=>deviceid,"sensor"=>"L0065"}.to_json, {content_type: :json, accept: :json}
testjson = JSON.parse(testbody)


@hourlist = []
@l65_list_max = []
@l65_list_min = []

l65_list = testjson['sensorHourlist']

l65_list.each { |x|
 @hourlist.push(x['hour'])
 @l65_list_max.push(x['max'])
 @l65_list_min.push(x['min'])
}

app/helpers/limoes_helper.rb
module LimoesHelper
end

app/views/limoes/_show_aside.html.erb
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/superui/content/ui/img/photos/girl1.png" class="img-circle" alt="用户头像">
            </div>
            <div class="pull-left info">
                <p>Admin管理员</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> 在线</a>
            </div>
        </div>
        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- Sidebar Menu -->

            <ul class="sidebar-menu">
            <li class="header">主导航</li>
            <li class="treeview">
                    <%= link_to '主控台', limoes_show_mains_path(params[:deviceid], params[:date]) %>
            </li>
            <li class="treeview">
                <a href="javascript:void(0);">
                    <i class="fa fa-share"></i> <span>立磨温度报表</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                    <%= link_to '最大值&平均值', limoes_show_temperature_path(params[:deviceid], params[:date]) %>
                    </li>
                    <li>
                       <%= link_to '最大值&极限值', limoes_show_temperature_topvalue_path(params[:deviceid], params[:date]) %>
                    </li>
                    <li>   <%= link_to '24h温度走势', limoes_show_temperature_24h_path(params[:deviceid], params[:date]) %></li>
                    <li>   <%= link_to '超限制统计', limoes_show_temperature_boxplot_path(params[:deviceid], params[:date]) %></li>
                </ul>
            </li>
          <li class="treeview">
                <a href="javascript:void(0);">
                    <i class="fa fa-share"></i> <span>立磨压力报表</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                    <%= link_to '最大值&最小值', limoes_show_pressure_path(params[:deviceid], params[:date]) %>
                    </li>
                    <li>
                       <%= link_to '平均值&极限值', limoes_show_pressure_topvalue_path(params[:deviceid], params[:date]) %>
                    </li>
                    <li>   <%= link_to '24h压力走势', limoes_show_pressure_24h_path(params[:deviceid], params[:date]) %></li>
                </ul>
            </li>

                   <li class="treeview">
                <a href="javascript:void(0);">
                    <i class="fa fa-share"></i> <span>立磨振动报表</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                    <%= link_to '最大值&最小值', limoes_show_vibration_path(params[:deviceid], params[:date]) %>
                    </li>
                    <li>
                       <%= link_to '平均值&极限值', limoes_show_vibration_topvalue_path(params[:deviceid], params[:date]) %>
                    </li>
                    <li>   <%= link_to '24h压力走势', limoes_show_vibration_24h_path(params[:deviceid], params[:date]) %></li>
                </ul>
            </li>

                      <li class="treeview">
                <a href="javascript:void(0);">
                    <i class="fa fa-share"></i> <span>立磨转速报表</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                    <%= link_to '转速7天统计', limoes_show_speed_path(params[:deviceid],"L0003", params[:date]) %>
                    </li>
                    <li>   <%= link_to '24h转速走势', limoes_show_speed_24h_path(params[:deviceid], "L0003", params[:date]) %></li>
                </ul>
            </li>
        </ul>
            <!-- /.sidebar-menu -->
</section>
    <!-- /.sidebar -->
</aside>

app/views/limoes/show_mains.html.erb
<%= render "show_aside"  %>
<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

<section class="content-header">
    <h1>

        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 首页</a></li>
        <li class="active">主控台</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3><%= @restart %>
                  <sup style="font-size: 20px">次</sup>
                </h3>
                <p> 停机次数</p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="#" class="small-box-footer">更多 <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3><%= @spendtime %><sup style="font-size: 20px">小时</sup>
                </h3>
                <p>工作时长</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer">更多 <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3><%= @avgSpendtime %>
                  <sup style="font-size: 20px">KW</sup>
                </h3>
                <p>耗电量</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">更多<i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3><%= @sumcount %>
                  <sup style="font-size: 20px">次</sup>
                </h3>
                <p>超限次数</p>
            </div>
            <div class="icon">
                <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">更多 <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<!-- /.row -->
<!-- Main row -->
<div class="row">
<!-- Left col -->
<section class="col-lg-6 connectedSortable">
<!-- Custom tabs (Charts with tabs)-->
<div class="nav-tabs-custom" style="width: 100%; height: 400px;" >
    <!-- Tabs within a box -->
    <ul class="nav nav-tabs pull-right">
        <li class="active"><a href="#revenue-chart" data-toggle="tab">工作时长图表</a></li>
        <li><a href="#pieChart" data-toggle="tab">工作时长占比</a></li>
        <li class="pull-left header"><i class="fa fa-inbox"></i>工作时长统计</li>
    </ul>
    <div class="tab-content no-padding">
        <div id="revenue-chart"  class="chart tab-pane active" style="height:300px;width: 560px"  ></div>
        <div id="pieChart" style="position: relative; height: 300px; width: 600px" class="chart tab-pane " ></div>
    </div>
</div>
<!-- /.nav-tabs-custom -->
<!-- TO DO List -->
  <div class="box box-solid ">
              <div class="box-body">
                    <div class="chart">
                        <div id="timeline" style="width: 100%; height: 400px;"></div>
                    </div>

                </div>
    </div>

<!-- /.box -->
<!-- quick email widget -->
</section>
<!-- /.Left col -->
<!-- right col (We are only adding the ID to make the widgets sortable)-->
<section class="col-lg-6 connectedSortable">
    <!-- Map box -->
    <!-- /.box -->
    <!-- solid sales graph -->
    <div class="box box-solid">
               <div class="box-body">
                    <div class="chart">
                        <div id="restart_count" style="width: 100%; height: 400px;"></div>
                    </div>

                </div>
        <!-- /.box-footer -->
    </div>
    <!-- /.box -->
    <!-- Calendar -->
    <div class="box box-solid ">
              <div class="box-body">
                    <div class="chart">
                        <div id="power" style="width: 100%; height: 400px;"></div>
                    </div>

                </div>

    </div>
    <!-- /.box -->
</section>
<!-- right col -->
</div>
<!-- /.row (main row) -->
</section>
</div>
    <script src="/superui/content/ui/global/jQuery/jquery.min.js"></script>
 <script src="/superui/content/plugins/echarts.min.js" charset="utf-8"></script>

   <script>
      var datelist = <%=raw @datelist %>;
       var spendtimes = <%=raw @spendtimes %>;
            // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('revenue-chart'));

        var restarts = <%=raw @restarts %>;

        var totalSpendtime = <%= @totalSpendtime %>;

        var avgSpendtimes = <%=raw @avgSpendtimes %>

        var periodlist = <%=raw @periodlist  %>
        var sumlist = <%=raw @sumlist %>

        var timlinedatas = []

        for (var i=0;i<sumlist.length;i++)
          {
            var timelinedata = {name:periodlist[i] , value:sumlist[i]}
            timlinedatas.push(timelinedata)
          }

        // 指定图表的配置项和数据
option = {
    tooltip : {
        trigger: 'axis'
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : datelist
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'工作时长',
            type:'line',
            smooth:true,
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:spendtimes
        }
    ],
    color: ['#337ab7']
};

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);




            // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('restart_count'));

        // 指定图表的配置项和数据
option = {
    title : {
        text: '七日内停机次数',
    },
    tooltip : {
        trigger: 'axis'
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            data : datelist
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'停机次数',
            type:'bar',
            data: restarts
        }
    ],
    color: ['#00a65a']
};
        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

            // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('pieChart'));

        // 指定图表的配置项和数据
  var option = {
    title : {
        text: '工作时长/停机时长',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    calculable : true,
    series : [
        {
            name:'访问来源',
            type:'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[
                {value:totalSpendtime, name:'工作时长'},
                {value:(168 - totalSpendtime), name:'停机时长'},
            ]
        }
    ]
};

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);


            // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('power'));

        // 指定图表的配置项和数据
option = {
    title : {
        text: '设备功耗',
    },
    tooltip : {
        trigger: 'axis'
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : datelist
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'用电量',
            type:'line',
            smooth:true,
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:avgSpendtimes
        }
    ]
};

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);



            // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('timeline'));

        // 指定图表的配置项和数据
        option = {
        title : {
        text: '超限值分布',
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    calculable : true,
    series : [
        {
            name:'超限值分布',
            type:'pie',
            radius : ['50%', '70%'],
            itemStyle : {
                normal : {
                    label : {
                        show : false
                    },
                    labelLine : {
                        show : false
                    }
                },
                emphasis : {
                    label : {
                        show : true,
                        position : 'center',
                        textStyle : {
                            fontSize : '22',
                            fontWeight : 'bold'
                        }
                    }
                }
            },
            data:timlinedatas
        }
    ]
};

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

    </script>