config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get "/:deviceid/:date/show_mains" => "limoes#show_mains", :as => "limoes_show_mains"
get "/:deviceid/:date/show_temperature" => "limoes#show_temperature",  :as => "limoes_show_temperature"
get "/:deviceid/:date/show_temperature_topvalue" => "limoes#show_temperature_topvalue",  :as => "limoes_show_temperature_topvalue"
get "/:deviceid/:date/show_temperature_24h" => "limoes#show_temperature_24h",  :as => "limoes_show_temperature_24h"
get "/:deviceid/:date/show_temperature_boxplot" => "limoes#show_temperature_boxplot",  :as => "limoes_show_temperature_boxplot"
get "/show_index" => "index#index", :as => "show_index"
get "/show_log" => "index#show_log", :as => "show_log"

get "/:deviceid/:date/show_pressure" => "limoes#show_pressure",  :as => "limoes_show_pressure"
get "/:deviceid/:date/show_pressure_topvalue" => "limoes#show_pressure_topvalue",  :as => "limoes_show_pressure_topvalue"
get "/:deviceid/:date/show_pressure_24h" => "limoes#show_pressure_24h",  :as => "limoes_show_pressure_24h"

get "/:deviceid/:sensor/:date/show_speed" => "limoes#show_speed",  :as => "limoes_show_speed"
get "/:deviceid/:sensor/:date/show_speed_topvalue" => "limoes#show_speed_topvalue",  :as => "limoes_show_speed_topvalue"
get "/:deviceid/:sensor/:date/show_speed_24h" => "limoes#show_speed_24h",  :as => "limoes_show_speed_24h"

get "/:deviceid/:date/show_vibration" => "limoes#show_vibration",  :as => "limoes_show_vibration"
get "/:deviceid/:date/show_vibration_topvalue" => "limoes#show_vibration_topvalue",  :as => "limoes_show_vibration_topvalue"
get "/:deviceid/:date/show_vibration_24h" => "limoes#show_vibration_24h",  :as => "limoes_show_vibration_24h"

end

app/views/index/_aside.html.erb
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/superui/content/ui/img/photos/girl1.png" class="img-circle" alt="用户头像">
            </div>
            <div class="pull-left info">
                <p>Admin管理员</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> 在线</a>
            </div>
        </div>
        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- Sidebar Menu -->

            <ul class="sidebar-menu">
            <li class="header">主导航</li>
            <li class="treeview">
                    <%= link_to '设备列表', show_index_url %>
            </li>
            <li class="treeview">
                <a href="javascript:void(0);">
                    <i class="fa fa-share"></i> <span>日志统计</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                        <li>
                    <%= link_to '设备上报数据统计', show_log_url %>
                    </li>
                </ul>
            </li>
        </ul>

            <!-- /.sidebar-menu -->
</section>
    <!-- /.sidebar -->
</aside>

app/views/index/index.html.erb

        <link href="/superui/content/plugins/bootstrap-table/bootstrap-table.css" rel="stylesheet" />
<%= render "aside"  %>
<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">



    <section class="content-header">
        <h1>
             管理表格
            <small>bootstrap-table管理表格</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Simple</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">

        <div class="row">
                <!-- BEGIN SAMPLE TABLE PORTLET-->
                <div class="col-md-12">
                    <!-- BEGIN SAMPLE TABLE PORTLET-->
                    <div class="box-body" style="padding-bottom:0px;">

                        <div class="table-scrollable">
                            <table class="table-striped table-hover" id="table"
                                   data-toggle="table"
                                   data-pagination="true"
                                   data-side-pagination="server"
                                   data-search="true"
                                   data-advanced-search="true"
                                 data-toolbar="#toolbar" data-row-style="rowStyle">
                                <thead>
                                    <tr>
                                        <th data-field="id" data-sortable="true">Id</th>
                                        <th data-field="lastname" data-sortable="true">设备编号</th>
                                        <th data-field="state" data-sortable="true" >设备类型</th>
                                    </tr>
                                </thead>
                                <tbody>

    <% @devices.each_with_index do |device,index| %>
 <tr class="active">
 <td style=""><%= (index+1) %></td>
 <td style=""><%= link_to device['deviceid'], limoes_show_mains_path(device['deviceid'],@findday) %></td>
 <td style=""> <span class="label label-sm label-success"> <%= t(device['type']) %> </span>
 </td>
 </tr>
<% end %>


                                </tbody>


                            </table>
                        </div>
                    </div>
                    <!-- END SAMPLE TABLE PORTLET-->

                </div>


        </div>

    </section>
</div>
    <script src="/superui/content/ui/global/jQuery/jquery.min.js"></script>
    <script src="/superui/content/ui/global/bootstrap/js/bootstrap.min.js"></script>
<script src="/superui/content/plugins/bootstrap-table/bootstrap-table.js"></script>
<script src="/superui/content/plugins/bootstrap-table/locale/bootstrap-table-zh-CN.js"></script>
</body>

app/views/index/show_log.html.erb
<%= render "aside"  %>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
 <section class="content-header">
        <h1>
             立磨温度报表
            <small>echarts sample</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Charts</a></li>
            <li class="active">设备上报数据统计</li>
        </ol>
    </section>
    <!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-md-12">

            <!-- AREA CHART -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">上报数据统计分布 </h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="chart">
                        <div id="main" style="width: 100%; height: 600px;"></div>
                    </div>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>

    </div>
    <!-- /.row -->
</section>


</div>
    <script src="/superui/content/ui/global/jQuery/jquery.min.js"></script>
 <script src="/superui/content/echarts.js" charset="utf-8"></script>

   <script>
   $(function () {


     var count_array = <%=raw @count_arr %>;
            // 基于准备好的dom，初始化echarts实例
            var myChart = echarts.init(document.getElementById('main'));

function getVirtulData(year) {
    year = year || '2017';
    var date = +echarts.number.parseDate(year + '-01-01');
    var end = +echarts.number.parseDate((+year + 1) + '-01-01');
    var dayTime = 3600 * 24 * 1000;
    var data = [];
    for (var time = date; time < end; time += dayTime) {
        data.push([
            echarts.format.formatTime('yyyy-MM-dd', time),
            Math.floor(Math.random() * 10000)
        ]);
    }
    return data;
}

var data = getVirtulData(2017)

console.log(data)
console.log(count_array)


option = {
    backgroundColor: '#404a59',

    title: {
        top: 30,
        text: '2017年每天数据量',
        left: 'center',
        textStyle: {
            color: '#fff'
        }
    },
    tooltip : {
        trigger: 'item'
    },
    legend: {
        top: '30',
        left: '100',
        data:['数据量', 'Top 5'],
        textStyle: {
            color: '#fff'
        }
    },
    calendar: [{
        top: 100,
        left: 'center',
        range: ['2017-01-01', '2017-06-30'],
        splitLine: {
            show: true,
            lineStyle: {
                color: '#000',
                width: 4,
                type: 'solid'
            }
        },
        yearLabel: {
            formatter: '{start}  1st',
            textStyle: {
                color: '#fff'
            }
        },
        itemStyle: {
            normal: {
                color: '#323c48',
                borderWidth: 1,
                borderColor: '#111'
            }
        }
    }, {
        top: 340,
        left: 'center',
        range: ['2017-07-01', '2017-12-31'],
        splitLine: {
            show: true,
            lineStyle: {
                color: '#000',
                width: 4,
                type: 'solid'
            }
        },
        yearLabel: {
            formatter: '{start}  2nd',
            textStyle: {
                color: '#fff'
            }
        },
        itemStyle: {
            normal: {
                color: '#323c48',
                borderWidth: 1,
                borderColor: '#111'
            }
        }
    }],
    series : [
        {
            name: '数据量',
            type: 'scatter',
            coordinateSystem: 'calendar',
            data: count_array,
            symbolSize: function (val) {
                return val[1] / 500000;
            },
            itemStyle: {
                normal: {
                    color: '#ddb926'
                }
            }
        },
        {
            name: '数据量',
            type: 'scatter',
            coordinateSystem: 'calendar',
            calendarIndex: 1,
            data: count_array,
            symbolSize: function (val) {
                return val[1] / 500000;
            },
            itemStyle: {
                normal: {
                    color: '#ddb926'
                }
            }
        },
        {
            name: 'Top 5',
            type: 'effectScatter',
            coordinateSystem: 'calendar',
            calendarIndex: 1,
            data: count_array.sort(function (a, b) {
                return b[1] - a[1];
            }).slice(0, 5),
            symbolSize: function (val) {
                return val[1] / 500000;
            },
            showEffectOn: 'render',
            rippleEffect: {
                brushType: 'stroke'
            },
            hoverAnimation: true,
            itemStyle: {
                normal: {
                    color: '#f4e925',
                    shadowBlur: 10,
                    shadowColor: '#333'
                }
            },
            zlevel: 1
        },
        {
            name: 'Top 5',
            type: 'effectScatter',
            coordinateSystem: 'calendar',
            data: count_array.sort(function (a, b) {
                return b[1] - a[1];
            }).slice(0, 5),
            symbolSize: function (val) {
                return val[1] / 500000;
            },
            showEffectOn: 'render',
            rippleEffect: {
                brushType: 'stroke'
            },
            hoverAnimation: true,
            itemStyle: {
                normal: {
                    color: '#f4e925',
                    shadowBlur: 10,
                    shadowColor: '#333'
                }
            },
            zlevel: 1
        }
    ]
};


            // 使用刚指定的配置项和数据显示图表。
            myChart.setOption(option);
        });

    </script>